Make getBranchForMilestone() explictly request the CSV data.
This fixes the following crash:
Traceback (most recent call last):
  File "/usr/local/google/home/pliard/ssd/depot_tools/drover.py", line 682, in <module>
    sys.exit(main())
  File "/usr/local/google/home/pliard/ssd/depot_tools/drover.py", line 678, in main
    return drover(options, args)
  File "/usr/local/google/home/pliard/ssd/depot_tools/drover.py", line 493, in drover
    options.branch = getBranchForMilestone(options.milestone)
  File "/usr/local/google/home/pliard/ssd/depot_tools/drover.py", line 393, in getBranchForMilestone
    version = string.split(parameters[2], '.')
IndexError: list index out of range
Sending crash report ...
  args: ['/usr/local/google/home/pliard/ssd/depot_tools/drover.py', '--merge', '175139', '--milestone', '25']
  cwd: /mnt/ssd/pliard/chromium/src/drover
  exception: list index out of range
  host: vox.par.corp.google.com
  stack:   File "/usr/local/google/home/pliard/ssd/depot_to
  user: pliard
  version: 2.7.3 (default, Aug  1 2012, 05:14:39)
[GCC 4.6.3

This function is called when the --milestone switch is provided. It requests
omahaproxy to fetch the branch corresponding to the provided milestone.
This function expects some CSV data coming from omahaproxy although it appeared
to actually receive the same HTML data that a browser receives when requesting
http://omahaproxy.appspot.com (user agent issue?).


Review URL: https://chromiumcodereview.appspot.com/11801007

git-svn-id: http://src.chromium.org/chrome/trunk/tools/depot_tools@175337 4ff67af0-8c30-449e-8e8b-ad334ec8d88c